import {BASE,COMPOUNDS,createCatalog} from './core.js?v=20260913-stars4';
import {CHARACTERS,portrait} from './characters.js?v=20260913-stars4';
const installLink=document.createElement('a');installLink.href='install.html';installLink.textContent='🐰 iPad 加入主畫面教學 →';document.querySelector('.teacher-links').append(installLink);
const update=document.createElement('section');update.innerHTML=`<h2>圖像操作與角色收藏</h2><p>學生頁改用大圖示、角色和語音提示。15 號為老師測試座號，正式練習另存測試紀錄。搶答、角色交易、密碼驗證與每日星星上限已發布；老師試玩不會寫入正式紀錄。</p><ul><li>輪流：先選兩位不同座號與角色，以藍／橘底色區分。換人會出現放大的角色，點角色才開始播題。</li><li>搶答：兩人站在同一大螢幕的左右兩邊。聽完看到閃電才可答，先答對得 1 分；答錯本題暫停。無法多人觸控的螢幕可用鍵盤：左方 A/S/D/F，右方 H/J/K/L。未實測你的大屏觸控硬體。</li><li>每回合：單人 10 題，雙人輪流每人 10 題，搶答共 10 題。混合聽音全對得 2 星；拼音全對得 3 星，有答錯的單人回合沒有當回合星星。全對指 10 題第一次都答對。</li><li>毅力星星：混合聽音每完整玩完 3 回合另得 1 星；拼音每完整玩完 2 回合另得 1 星。兩種進度分開，不互相疊加；中途離開不計次數。按座號保存，重新整理不清空、不重複給獎勵。</li><li>比賽獎勵：輪流／搶答贏家 2 星、輸家 1 星，平手各 1 星；不疊加單人全對獎勵，仍可累積該類關卡的毅力進度。比賽分數與可抽角色的星星分開。</li><li>轉蛋：5 星星一次，動物池／精靈池各 10 個角色，同池等機率，可重複。重複角色換 1 糖果；50 糖果自選兌換一個尚未擁有的角色。免費、不涉及付費。</li><li>兩個起始角色為棉花兔、橘子狐，其餘可抽取或兌換。預覽收藏只存在目前瀏覽器，不是正式後台存檔。</li><li>要快速測試兌換：選 15 號，展開「老師試玩設定」，按「試玩補充：20 星星＋50 糖果」。這個按鈕只出現在試玩模式。</li></ul><h2>20 個角色・森林小夥伴</h2><p>原創毛絨、針織與花葉造型。月光慵懶、雪晶安靜、森林認真、星河驚訝、莓果俏皮；保留原本角色編號，既有收藏不用重抽。之後可從角色清單擴充，不限 20 個；新角色正式開放時須同步部署前後台。</p><div class="teacher-character-grid">${CHARACTERS.map(c=>`<article>${portrait(c)}<b>${c.name}</b></article>`).join('')}</div><h2>拼音音檔已放慢</h2><p>新版保留完整音節，語速由 -2 改為 -4，前留 0.2 秒、後留 0.6 秒停頓，仍只念一次。下方 44 個示範已改用慢速版；原版保留於各音節的比較選單。請老師確認聲調與自然度後再開放學生拼音。</p>`;
document.querySelector('.teacher-links').after(update);
const listeningHelp=document.createElement('section');listeningHelp.innerHTML='<h2>一個聽音關卡，混合三類已教符號</h2><p>兔子關卡已整合聲符、韻符、結合韻。把已教內容填入「今日任務」A 欄，每格一個完整符號或結合韻；例如 ㄅ、ㄠ、ㄧㄠ 分別放三格。不會拆開 ㄧㄠ，也不會自動加入未教內容。當 ㄠ 和 ㄧㄠ 都已教過時，選項會優先讓它們一起出現，練習辨別。</p><p>原本的結合韻鎖頭已移除，不需另外解鎖。拼音鎖頭請先到下方聽音，確認後在私人試算表「遊戲設定」B3 勾選「拼音示範音已確認」，再回遊戲按 ⟳。目前只提供 44 個拼音音節，不是任意組合都已有錄音。</p>';update.before(listeningHelp);
const dailyHelp=document.createElement('section');dailyHelp.innerHTML='<h2>每日星星上限</h2><p>每位學生、每個關卡分別計算，台灣時間午夜更新。合併後的聽音關卡每天最多 4 顆全對星、4 顆毅力星（全對兩回合領滿全對星；完整遊玩 12 回合可累積 4 顆毅力星）；拼音每天最多 12 顆全對星、5 顆毅力星。達上限仍可練習、照常記錄成績，已領星星不追扣。轉蛋花掉星星不會恢復當日額度。對戰勝負星星目前不設上限，對戰產生的毅力星仍受各關卡每日上限限制。</p>';document.querySelector('main').append(dailyHelp);
const pinAdmin=document.createElement('section');pinAdmin.innerHTML='<h2>學生的 4 位數密碼</h2><p>正式版由私人 Google 試算表的「學生密碼」分頁管理。每位學生一列，在「輸入新4位密碼」填入四位數字，即可設定或重設；可以用 0 開頭。成功後輸入欄會清空，舊登入失效。忘記密碼時只能重設，不在公開網頁顯示原密碼。</p><p>登入與邀請同學時各自驗證。連續錯五次暫停五分鐘，老師重設可解除。正式版由密碼後台驗證身分；設定或重設密碼後，請以正式遊戲測試登入。</p><details><summary>老師試玩密碼設定（只影響本瀏覽器，不是正式密碼）</summary><p>試玩預設密碼為 1234，包含 15 號。下方可修改試玩密碼；修改後請重新整理遊戲再測試。</p><form id="demo-pin-form"><label>座號 <select id="demo-pin-seat">'+Array.from({length:15},(_,i)=>{const s=String(i+1).padStart(2,'0');return `<option value="${s}" ${s==='15'?'selected':''}>${s}</option>`;}).join('')+'</select></label> <label>新試玩密碼 <input id="demo-new-pin" type="password" inputmode="numeric" autocomplete="new-password" pattern="[0-9]{4}" minlength="4" maxlength="4" required aria-label="四位數試玩密碼"></label> <button class="primary" type="submit">儲存試玩密碼</button><p id="demo-pin-status" role="status"></p></form></details>';
update.before(pinAdmin);
document.getElementById('demo-pin-form').onsubmit=e=>{e.preventDefault();const input=document.getElementById('demo-new-pin'),seat=document.getElementById('demo-pin-seat').value;if(!/^\d{4}$/.test(input.value))return;try{const pins=JSON.parse(localStorage.getItem('zhuyin.demo.pins.v1')||'{}');pins[seat]=input.value;localStorage.setItem('zhuyin.demo.pins.v1',JSON.stringify(pins));sessionStorage.removeItem('zhuyin.demo.pin-fails.'+seat);input.value='';document.getElementById('demo-pin-status').textContent=seat+' 號試玩密碼已儲存；請重新整理遊戲。';}catch{document.getElementById('demo-pin-status').textContent='瀏覽器無法保存，請確認不是禁止儲存的模式。';}};
const teacherStyle=document.createElement('style');teacherStyle.textContent='.teacher-character-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px}.teacher-character-grid article{background:#fff;border:1px solid #dae3db;border-radius:18px;padding:10px;text-align:center}.teacher-character-grid img{width:100%;height:135px}.teacher-character-grid b{display:block;font-size:14px}.teacher-page li{line-height:1.9;color:#617b74}';document.head.append(teacherStyle);
function add(container,label,file){const card=document.createElement('article');card.className='audio-item';const title=document.createElement('b');title.textContent=label;const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=file;audio.setAttribute('aria-label',label+' 發音');audio.onplay=()=>document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause();});card.append(title,audio);document.getElementById(container).append(card);}
COMPOUNDS.forEach((s,i)=>add('compounds',s,'audio/compound/c'+String(i+1).padStart(2,'0')+'.mp3'));
BASE.forEach((s,i)=>add('base',s,'audio/audio_F'+(i+1)+'.WAV'));
try{const rows=await fetch('data/syllables.json').then(r=>r.json());createCatalog(rows).forEach(s=>{add('syllables',s.label+' · '+s.word,s.audio);const card=document.getElementById('syllables').lastElementChild,details=document.createElement('details'),summary=document.createElement('summary'),old=document.createElement('audio');summary.textContent='比較原版';old.controls=true;old.preload='none';old.src=s.audio.replace('syllable-clear/','syllable/');old.setAttribute('aria-label',s.label+' 原版發音');old.onplay=()=>document.querySelectorAll('audio').forEach(other=>{if(other!==old)other.pause();});details.append(summary,old);card.append(details);});}catch{document.getElementById('syllables').textContent='素材清單讀取失敗，請重新整理。';}
